version: 2.1

executors:
  default:
    working_directory: ~/repo
    docker:
      - image: lambci/lambda:build-nodejs10.x

jobs:
  build:
    executor:
      name: default

    steps:
      - checkout

      - restore_cache:
          keys:
          - v3-dependencies-{{ checksum "package.json" }}
          - v3-dependencies-

      - run: npm install
      - run: npm run all-install

      - save_cache:
          paths:
            - node_modules
          key: v3-dependencies-{{ checksum "package.json" }}

      - run:
          name: Check coding standard by ESLint
          command: npm run lint

      - run:
          name: Run lambdaEdge test
          command: npm run test-lambdaedge

      - run:
          name: Run originResponse test
          command: npm run test-originresponse

      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*
  deploy-stage:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: deploy edge for dev
          command: npm run deploy:edge -- --stage development
      - deploy:
          name: deploy origin for dev
          command: npm run deploy:origin -- --stage development
      - deploy:
          name: deploy edge for stage
          command: npm run deploy:edge -- --stage staging
      - deploy:
          name: deploy origin for stage
          command: npm run deploy:origin -- --stage staging
  deploy-prod:
    executor:
      name: default
    steps:
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: deploy edge for prod
          command: npm run deploy:edge -- --stage production
      - deploy:
          name: deploy origin for prod
          command: npm run deploy:origin -- --stage production
workflows:
  version: 2
  build-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy-stage:
          requires:
            - build
          filters:
            branches:
              only: master
      - deploy-prod:
          requires:
            - build
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
